<a href="https://colab.research.google.com/github/raolbrito/Matriz/blob/master/aula%203%20Prof.%20Mauro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Estruturas de dados em Python


### Variáveis

In [1]:
x = 3
nome = "Mauro"
logica = True

In [2]:
nome1 = "Mauro"
nome2 = "Bete"
nome3 = "Pedro"

### Listas


In [3]:
nomes = ["Mauro","Bete","Pedro"]
nomes = [nome1,nome2,nome3]
nomes.append("João")
print(nomes)

['Mauro', 'Bete', 'Pedro', 'João']


In [4]:
nomes.remove("Mauro")
print(nomes)
nomes.remove("Maria")

['Bete', 'Pedro', 'João']


ValueError: ignored

In [5]:
"Maria" in nomes

False

In [6]:
if "Maria" in nomes:
  nomes.remove("Maria")
else:
  print("Não tem maria em nomes")


Não tem maria em nomes


In [7]:
for nome in nomes:
  print(nome)

Bete
Pedro
João


## Tuplas

In [8]:
primos = (1,2,3,5,7,11,13,17,23)
print(primos)
primo_par = 2,
print(primo_par)

(1, 2, 3, 5, 7, 11, 13, 17, 23)
(2,)


## Dicionários

In [9]:
comida = {}

In [10]:
comida["feijoada"] = "Minha comida preferida"
comida["coentro"] = "Vixi, detesto!"
comida

{'coentro': 'Vixi, detesto!', 'feijoada': 'Minha comida preferida'}

In [11]:
comida["coentro"]

'Vixi, detesto!'

In [13]:
comida["queijo"] = "Uai, sou mineiro!"

In [14]:
print(comida)

{'feijoada': 'Minha comida preferida', 'coentro': 'Vixi, detesto!', 'queijo': 'Uai, sou mineiro!'}


In [15]:
if 'queijo' in comida:
  print("O que eu acho de queijo é: ")
  print(comida["queijo"])

O que eu acho de queijo é: 
Uai, sou mineiro!


In [16]:
del comida["coentro"]

In [17]:
print(comida)

{'feijoada': 'Minha comida preferida', 'queijo': 'Uai, sou mineiro!'}


In [18]:
for key in comida:
  print(key,' -> ',comida[key])

feijoada  ->  Minha comida preferida
queijo  ->  Uai, sou mineiro!


## Combinando estruturas de dados


In [19]:
eu = {"família" : nomes,
      "comidas" : comida}

In [20]:
print(eu)

{'família': ['Bete', 'Pedro', 'João'], 'comidas': {'feijoada': 'Minha comida preferida', 'queijo': 'Uai, sou mineiro!'}}


## Outros exemplos em estrutura de dados


In [24]:
print(nomes)
print(sorted(nomes))

['Bete', 'Pedro', 'João']
['Bete', 'João', 'Pedro']


In [23]:
print(type(nome1))
print(type(nomes))
print(type(primos))
print(type(eu))

<class 'str'>
<class 'list'>
<class 'tuple'>
<class 'dict'>


## Pandas

In [25]:
import pandas as pd
from pandas import Series, DataFrame

## Série

In [26]:
ser_1 = Series([1, 1, 2, -3, -5, 8, 13])
ser_1

0     1
1     1
2     2
3    -3
4    -5
5     8
6    13
dtype: int64

In [27]:
print(ser_1.index)
print(ser_1.values)


RangeIndex(start=0, stop=7, step=1)
[ 1  1  2 -3 -5  8 13]


In [28]:
ser_2 = Series([1, 1, 2, -3, -5], index=['a', 'b', 'c', 'd', 'e'])
ser_2

a    1
b    1
c    2
d   -3
e   -5
dtype: int64

In [29]:
ser_2['a']

1

In [30]:
ser_2[4] == ser_2['e']

True

In [32]:
ser_2[['c', 'a', 'b']]

c    2
a    1
b    1
dtype: int64

In [33]:
ser_2[ser_2 > 0]

a    1
b    1
c    2
dtype: int64

In [34]:
ser_2 * 2

a     2
b     2
c     4
d    -6
e   -10
dtype: int64

In [35]:
import numpy as np
np.exp(ser_2)

a    2.718282
b    2.718282
c    7.389056
d    0.049787
e    0.006738
dtype: float64

In [36]:
ser_3 = Series(eu)
ser_3

família                                  [Bete, Pedro, João]
comidas    {'feijoada': 'Minha comida preferida', 'queijo...
dtype: object

In [37]:
pd.isnull(ser_3)

família    False
comidas    False
dtype: bool

## Dataframe

In [38]:
info = {'estado' : ['MG', 'MG', 'MG', 'SP', 'SP'],
        'ano' : [2012, 2013, 2014, 2014, 2015],
        'pop' : [5.0, 5.1, 5.2, 4.0, 4.1]}
print(type(info))
df = DataFrame(info)
print(type(df))
print(df)

<class 'dict'>
<class 'pandas.core.frame.DataFrame'>
  estado   ano  pop
0     MG  2012  5.0
1     MG  2013  5.1
2     MG  2014  5.2
3     SP  2014  4.0
4     SP  2015  4.1


In [39]:
df = DataFrame(info, columns=['ano', 'estado', 'pop', 'desempregados'])
df

ano estado  pop desempregados
0  2012     MG  5.0           NaN
1  2013     MG  5.1           NaN
2  2014     MG  5.2           NaN
3  2014     SP  4.0           NaN
4  2015     SP  4.1           NaN

In [40]:
print(df['ano'])
print(df.desempregados)

0    2012
1    2013
2    2014
3    2014
4    2015
Name: ano, dtype: int64
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: desempregados, dtype: object


In [41]:
df.iloc[4]

ano              2015
estado             SP
pop               4.1
desempregados     NaN
Name: 4, dtype: object

In [43]:
type(df.iloc[4])

pandas.core.series.Series

In [44]:
df.desempregados = np.random.rand(5) * 1000000
df

ano estado  pop  desempregados
0  2012     MG  5.0  550397.543083
1  2013     MG  5.1  213446.311589
2  2014     MG  5.2  313898.119194
3  2014     SP  4.0  336701.649154
4  2015     SP  4.1  571192.127062

In [45]:
df.desempregados = df.desempregados.astype(int)
df

ano estado  pop  desempregados
0  2012     MG  5.0         550397
1  2013     MG  5.1         213446
2  2014     MG  5.2         313898
3  2014     SP  4.0         336701
4  2015     SP  4.1         571192

In [46]:
desempregados = Series([454333, 232111, 242422], index=[2, 3, 4])
df.desempregados = desempregados
df

ano estado  pop  desempregados
0  2012     MG  5.0            NaN
1  2013     MG  5.1            NaN
2  2014     MG  5.2       454333.0
3  2014     SP  4.0       232111.0
4  2015     SP  4.1       242422.0

In [47]:
df['nonsense'] = df.ano * df.desempregados
df

ano estado  pop  desempregados     nonsense
0  2012     MG  5.0            NaN          NaN
1  2013     MG  5.1            NaN          NaN
2  2014     MG  5.2       454333.0  915026662.0
3  2014     SP  4.0       232111.0  467471554.0
4  2015     SP  4.1       242422.0  488480330.0

In [48]:
del df['nonsense']
df

ano estado  pop  desempregados
0  2012     MG  5.0            NaN
1  2013     MG  5.1            NaN
2  2014     MG  5.2       454333.0
3  2014     SP  4.0       232111.0
4  2015     SP  4.1       242422.0

In [49]:
df2 = df[['ano','pop']]
df

ano estado  pop  desempregados
0  2012     MG  5.0            NaN
1  2013     MG  5.1            NaN
2  2014     MG  5.2       454333.0
3  2014     SP  4.0       232111.0
4  2015     SP  4.1       242422.0

In [50]:
df2.T

0       1       2       3       4
ano  2012.0  2013.0  2014.0  2014.0  2015.0
pop     5.0     5.1     5.2     4.0     4.1

In [51]:
df.values

array([[2012, 'MG', 5.0, nan],
       [2013, 'MG', 5.1, nan],
       [2014, 'MG', 5.2, 454333.0],
       [2014, 'SP', 4.0, 232111.0],
       [2015, 'SP', 4.1, 242422.0]], dtype=object)

In [52]:
type(df.values)

numpy.ndarray

In [53]:
df2 = df.copy()
df.drop([0, 1])

ano estado  pop  desempregados
2  2014     MG  5.2       454333.0
3  2014     SP  4.0       232111.0
4  2015     SP  4.1       242422.0

In [54]:
df2

ano estado  pop  desempregados
0  2012     MG  5.0            NaN
1  2013     MG  5.1            NaN
2  2014     MG  5.2       454333.0
3  2014     SP  4.0       232111.0
4  2015     SP  4.1       242422.0

In [55]:
df2.ano > 2013

0    False
1    False
2     True
3     True
4     True
Name: ano, dtype: bool

In [56]:
df2[df2.ano > 2013]

ano estado  pop  desempregados
2  2014     MG  5.2       454333.0
3  2014     SP  4.0       232111.0
4  2015     SP  4.1       242422.0

In [57]:
df2.iloc[2:4]

ano estado  pop  desempregados
2  2014     MG  5.2       454333.0
3  2014     SP  4.0       232111.0

In [58]:
df2.iloc[2:4].pop

<bound method NDFrame.pop of     ano estado  pop  desempregados
2  2014     MG  5.2       454333.0
3  2014     SP  4.0       232111.0>

## Numpy arrays

### Criando arrays

In [59]:
import numpy as np

a = np.array([1, 2, 3])   # Cria um vetor
print(type(a))            
print(a.shape)             
print(a[0], a[1], a[2])   
a[0] = 5                  
print(a)                  

b = np.array([[1,2,3],[4,5,6]])    # Cria uma matriz
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])   

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [60]:
a = np.zeros((2,2))   #Cria array de zeros
print(a)              
                      

b = np.ones((1,2))    # Cria array de "1s"
print(b)              

c = np.full((2,2), 7) # Array constante 
print(c)               
                       

d = np.eye(2)         # Matriz-identidade
print(d)              

e = np.random.random((2,2))  # Array de números aleatórios
print(e)                     
                             

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.88795211 0.12884117]
 [0.48413875 0.24767587]]


### Indexando arrays

In [61]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Usando slicing para obter sub-array com as primeiras 2 linhas
# e as colunas 1 e 2

b = a[:2, 1:3]
print(b)

# Uma fatia de um array é uma VISÃO desse mesmo array. Isso significa
# que modificar um elemento de "b" mudará o valor em "a".
print(a[0, 1])  
b[0, 0] = 77    
print(a[0, 1])  

c = a[:2, 1:3].copy()
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77
[[77  3]
 [ 6  7]]


In [62]:
c[0, 0] = -1000
print(c)
print(a)

[[-1000     3]
 [    6     7]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [63]:
a > 10 # indexando

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [64]:
a[a > 10]

array([77, 11, 12])

### Operações com arrays

In [65]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [66]:
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]


In [67]:
print(np.sum(x)) 
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10.0
[4. 6.]
[3. 7.]


### Exercício

In [68]:
from google.colab import drive
drive.mount("/content/drive")

KeyboardInterrupt: ignored

In [ ]:
!ls drive/'My Drive'/Dados

In [ ]:
!pip install Pillow


In [ ]:
from PIL import Image
img = Image.open("drive/My Drive/Dados/gato.png")

In [ ]:
print(type(img))
imgnp = np.array(img)
print(type(imgnp))

In [ ]:
print(imgnp.shape)